import { useState } from "react";
import { Layout } from "../../Components/Sidebar";
import {
    BarChart,
    Bar,
    XAxis,
    YAxis,
    Tooltip,
    ResponsiveContainer,
    Cell,
    PieChart,
    Pie,
    Legend,
} from "recharts";
import {
    Users,
    Home,
    Package,
    TrendingUp,
    Activity,
    X,
    Search,
    Filter,
} from "lucide-react";

// ── Data ─────────────────────────────────────────────────────────────────────
const barangayData = [
    { name: "Banay-Banay", evacuees: 28 },
    { name: "Mamatid", evacuees: 24 },
    { name: "Sala", evacuees: 14 },
    { name: "Gulod", evacuees: 10 },
    { name: "Marinig", evacuees: 8 },
];

const vulnerableData = [
    { name: "Senior Citizens", value: 35, color: "#3b82f6" },
    { name: "Children", value: 40, color: "#22d3ee" },
    { name: "Pregnant", value: 15, color: "#f97316" },
    { name: "PWD", value: 10, color: "#a855f7" },
];

const INITIAL_RISK_MAP = [
    { name: "Marinig", risk: "high" },
    { name: "Bigaa", risk: "high" },
    { name: "Butong", risk: "high" },
    { name: "Gulod", risk: "high" },
    { name: "Mamatid", risk: "medium" },
    { name: "Banlic", risk: "medium" },
    { name: "Pulo", risk: "medium" },
    { name: "San Isidro", risk: "medium" },
    { name: "Sala", risk: "medium" },
    { name: "Niugan", risk: "medium" },
    { name: "Banay-Banay", risk: "low" },
    { name: "Tres Cruses", risk: "low" },
    { name: "Casile", risk: "low" },
    { name: "Pittland", risk: "low" },
    { name: "Diezmo", risk: "low" },
    { name: "Rechnon", risk: "low" },
    { name: "Uno", risk: "low" },
    { name: "Dos", risk: "low" },
    { name: "Tres", risk: "low" },
];

// Expanded initial data with categories for filtering
const INITIAL_LOGS = [
    {
        id: 1,
        color: "#0d9488",
        category: "Registration",
        text: "New family registered at Mamatid Elem. School",
        time: "10 mins ago",
    },
    {
        id: 2,
        color: "#0d9488",
        category: "Logistics",
        text: "Relief goods delivered to Sala Evacuation center",
        time: "1 hour ago",
    },
    {
        id: 3,
        color: "#f97316",
        category: "Alerts",
        text: "Banay-Banay Brgy Hall reached critical capacity",
        time: "2 hours ago",
    },
    {
        id: 4,
        color: "#3b82f6",
        category: "System",
        text: "System report generated by Admin User",
        time: "3 hours ago",
    },
    {
        id: 5,
        color: "#3b82f6",
        category: "Alerts",
        text: "New announcement published: Weather Alert",
        time: "5 hours ago",
    },
    {
        id: 6,
        color: "#3b82f6",
        category: "System",
        text: "Admin User logged into the system.",
        time: "Yesterday, 08:30 AM",
    },
    {
        id: 7,
        color: "#ef4444",
        category: "Alerts",
        text: "Emergency Alert: Typhoon Baesyang upgraded to Signal No. 2",
        time: "Yesterday, 06:00 AM",
    },
    {
        id: 8,
        color: "#0d9488",
        category: "Logistics",
        text: "New stock of Rice (50kg) received at Main Warehouse",
        time: "May 11, 2026",
    },
];

const riskColors = {
    high: { bg: "#ef4444", label: "text-white" },
    medium: { bg: "#f59e0b", label: "text-white" },
    low: { bg: "#22c55e", label: "text-white" },
};

// ── Stat Card ─────────────────────────────────────────────────────────────────
function StatCard({ icon: Icon, label, value, sub, iconBg }) {
    return (
        <div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border border-gray-100 dark:border-gray-700 flex items-start gap-4 transition-colors">
            <div className={`p-3 rounded-xl ${iconBg}`}>
                <Icon size={20} className="text-white" />
            </div>
            <div className="flex-1 min-w-0">
                <p className="text-xs text-gray-500 dark:text-gray-400 font-medium mb-0.5">
                    {label}
                </p>
                <p className="text-2xl font-bold text-gray-900 dark:text-white">
                    {value}
                </p>
                {sub && (
                    <p className="text-xs text-teal-600 dark:text-teal-400 font-medium mt-0.5 flex items-center gap-1">
                        <TrendingUp size={11} /> {sub}
                    </p>
                )}
            </div>
        </div>
    );
}

// ── Main Dashboard ────────────────────────────────────────────────────────────
export default function Dashboard() {
    const [riskMap, setRiskMap] = useState(INITIAL_RISK_MAP);

    // Logs State
    const [logs, setLogs] = useState(INITIAL_LOGS);
    const [isLogsModalOpen, setIsLogsModalOpen] = useState(false);
    const [logSearch, setLogSearch] = useState("");
    const [logFilter, setLogFilter] = useState("All");

    // Simulate incoming data
    const handleSimulateEvent = () => {
        const events = [
            {
                category: "Alerts",
                color: "#ef4444",
                text: "Emergency alert triggered in Brgy. Pulo!",
            },
            {
                category: "Logistics",
                color: "#0d9488",
                text: "New batch of hygiene kits arrived.",
            },
            {
                category: "Alerts",
                color: "#f97316",
                text: "Casile Evacuation Center nearing capacity.",
            },
            {
                category: "Registration",
                color: "#0d9488",
                text: "New evacuee profile created in Marinig.",
            },
        ];

        const randomEvent = events[Math.floor(Math.random() * events.length)];
        const newEvent = {
            id: Date.now(),
            color: randomEvent.color,
            category: randomEvent.category,
            text: randomEvent.text,
            time: "Just now",
        };

        // Add to top of the permanent logs array
        setLogs((prev) => [newEvent, ...prev]);
    };

    // Toggle risk level on map click
    const handleToggleRisk = (nameToToggle) => {
        setRiskMap((prevMap) =>
            prevMap.map((brgy) => {
                if (brgy.name === nameToToggle) {
                    const nextRisk =
                        brgy.risk === "low"
                            ? "medium"
                            : brgy.risk === "medium"
                              ? "high"
                              : "low";
                    return { ...brgy, risk: nextRisk };
                }
                return brgy;
            }),
        );
    };

    // Filter logs for the modal
    const filteredLogs = logs.filter((log) => {
        const matchesSearch = log.text
            .toLowerCase()
            .includes(logSearch.toLowerCase());
        const matchesFilter = logFilter === "All" || log.category === logFilter;
        return matchesSearch && matchesFilter;
    });

    return (
        <Layout
            currentPage="Dashboard"
            title="Dashboard"
            subtitle="Overview of evacuation operations and shelter status."
        >
            {/* Live badge */}
            <div className="flex justify-end mb-4">
                <span className="flex items-center gap-2 text-xs font-medium text-teal-700 dark:text-teal-300 bg-teal-50 dark:bg-teal-900/30 px-3 py-1.5 rounded-full border border-teal-100 dark:border-teal-800 transition-colors">
                    <span className="w-2 h-2 bg-teal-500 rounded-full animate-pulse" />
                    Live Updates Active
                </span>
            </div>

            {/* FULL LOGS MODAL */}
            {isLogsModalOpen && (
                <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/50 dark:bg-gray-900/80 backdrop-blur-sm transition-all">
                    <div className="bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-3xl overflow-hidden flex flex-col max-h-[85vh] animate-in zoom-in-95 duration-200">
                        {/* Modal Header */}
                        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-100 dark:border-gray-700">
                            <h2 className="text-lg font-bold text-gray-900 dark:text-white flex items-center gap-2">
                                <Activity
                                    size={20}
                                    className="text-teal-600 dark:text-teal-400"
                                />
                                System Activity Logs
                            </h2>
                            <button
                                onClick={() => setIsLogsModalOpen(false)}
                                className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300"
                            >
                                <X size={20} />
                            </button>
                        </div>

                        {/* Modal Toolbar (Filters) */}
                        <div className="px-6 py-4 border-b border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900/20 flex flex-col sm:flex-row gap-4">
                            <div className="relative flex-1">
                                <Search
                                    className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400 dark:text-gray-500"
                                    size={15}
                                />
                                <input
                                    type="text"
                                    placeholder="Search logs..."
                                    value={logSearch}
                                    onChange={(e) =>
                                        setLogSearch(e.target.value)
                                    }
                                    className="w-full pl-9 pr-4 py-2 border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-teal-500 transition-colors"
                                />
                            </div>
                            <div className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 dark:border-gray-700 rounded-lg bg-white dark:bg-gray-900 transition-colors">
                                <Filter
                                    size={14}
                                    className="text-gray-400 dark:text-gray-500"
                                />
                                <select
                                    value={logFilter}
                                    onChange={(e) =>
                                        setLogFilter(e.target.value)
                                    }
                                    className="text-sm text-gray-600 dark:text-gray-300 focus:outline-none bg-transparent"
                                >
                                    <option value="All">All Categories</option>
                                    <option value="Alerts">Alerts</option>
                                    <option value="Logistics">Logistics</option>
                                    <option value="Registration">
                                        Registration
                                    </option>
                                    <option value="System">System</option>
                                </select>
                            </div>
                        </div>

                        {/* Modal Scrollable Content */}
                        <div className="flex-1 overflow-y-auto p-6 space-y-5">
                            {filteredLogs.length === 0 ? (
                                <p className="text-center text-gray-500 dark:text-gray-400 py-10">
                                    No logs found matching your criteria.
                                </p>
                            ) : (
                                filteredLogs.map((log) => (
                                    <div
                                        key={log.id}
                                        className="flex gap-4 p-4 rounded-xl border border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-800/50 transition-colors"
                                    >
                                        <div
                                            className="w-2.5 h-2.5 rounded-full mt-1.5 flex-shrink-0"
                                            style={{
                                                backgroundColor: log.color,
                                            }}
                                        />
                                        <div className="flex-1">
                                            <div className="flex justify-between items-start mb-1">
                                                <p className="text-sm font-medium text-gray-800 dark:text-gray-200">
                                                    {log.text}
                                                </p>
                                                <span className="text-xs text-gray-400 dark:text-gray-500 whitespace-nowrap ml-4">
                                                    {log.time}
                                                </span>
                                            </div>
                                            <span className="text-[10px] font-semibold tracking-wide uppercase px-2 py-0.5 rounded-full bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 text-gray-500 dark:text-gray-400">
                                                {log.category}
                                            </span>
                                        </div>
                                    </div>
                                ))
                            )}
                        </div>
                    </div>
                </div>
            )}

            {/* Stat Cards */}
            <div className="grid grid-cols-2 xl:grid-cols-4 gap-4 mb-6">
                <StatCard
                    icon={Users}
                    label="Total Evacuees"
                    value="60"
                    sub="+125% from yesterday"
                    iconBg="bg-teal-500"
                />
                <StatCard
                    icon={Home}
                    label="Active Shelters"
                    value="6"
                    sub="2 nearing capacity"
                    iconBg="bg-blue-500"
                />
                <StatCard
                    icon={Package}
                    label="Relief Distributed"
                    value="10,370"
                    sub="Across 6 centers"
                    iconBg="bg-emerald-500"
                />
                <StatCard
                    icon={Users}
                    label="Families Registered"
                    value="15"
                    sub="+5 new today"
                    iconBg="bg-purple-500"
                />
            </div>

            {/* Charts Row */}
            <div className="grid grid-cols-1 xl:grid-cols-3 gap-4 mb-6">
                {/* Bar Chart */}
                <div className="xl:col-span-2 bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border border-gray-100 dark:border-gray-700 transition-colors">
                    <h3 className="font-semibold text-gray-800 dark:text-gray-100 mb-4 text-sm">
                        Evacuees per Barangay (Top 5)
                    </h3>
                    <div style={{ width: "99%", height: 200 }}>
                        <ResponsiveContainer>
                            <BarChart data={barangayData} barSize={32}>
                                <XAxis
                                    dataKey="name"
                                    tick={{ fontSize: 11, fill: "#9ca3af" }}
                                    axisLine={false}
                                    tickLine={false}
                                />
                                <YAxis
                                    tick={{ fontSize: 11, fill: "#9ca3af" }}
                                    axisLine={false}
                                    tickLine={false}
                                />
                                <Tooltip
                                    contentStyle={{
                                        borderRadius: 8,
                                        border: "none",
                                        boxShadow: "0 4px 16px rgba(0,0,0,0.1)",
                                    }}
                                    cursor={{ fill: "rgba(13, 148, 136, 0.1)" }}
                                />
                                <Bar dataKey="evacuees" radius={[6, 6, 0, 0]}>
                                    {barangayData.map((_, i) => (
                                        <Cell key={i} fill="#0d9488" />
                                    ))}
                                </Bar>
                            </BarChart>
                        </ResponsiveContainer>
                    </div>
                </div>

                {/* Pie Chart */}
                <div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border border-gray-100 dark:border-gray-700 transition-colors">
                    <h3 className="font-semibold text-gray-800 dark:text-gray-100 mb-2 text-sm">
                        Vulnerable Groups
                    </h3>
                    <div style={{ width: "99%", height: 200 }}>
                        <ResponsiveContainer>
                            <PieChart>
                                <Pie
                                    data={vulnerableData}
                                    cx="50%"
                                    cy="50%"
                                    innerRadius={55}
                                    outerRadius={80}
                                    paddingAngle={3}
                                    dataKey="value"
                                >
                                    {vulnerableData.map((entry, i) => (
                                        <Cell key={i} fill={entry.color} />
                                    ))}
                                </Pie>
                                <Legend
                                    iconType="circle"
                                    iconSize={8}
                                    formatter={(value) => (
                                        <span
                                            style={{
                                                fontSize: 11,
                                                color: "#9ca3af",
                                            }}
                                        >
                                            {value}
                                        </span>
                                    )}
                                />
                            </PieChart>
                        </ResponsiveContainer>
                    </div>
                </div>
            </div>

            {/* Bottom Row */}
            <div className="grid grid-cols-1 xl:grid-cols-3 gap-4">
                {/* Heat Map */}
                <div className="xl:col-span-2 bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border border-gray-100 dark:border-gray-700 transition-colors">
                    <div className="flex items-center justify-between mb-4">
                        <h3 className="font-semibold text-gray-800 dark:text-gray-100 text-sm">
                            Disaster Risk Heat Map
                        </h3>
                        <div className="flex items-center gap-3 text-xs text-gray-500 dark:text-gray-400">
                            <span className="flex items-center gap-1.5">
                                <span className="w-3 h-3 rounded-sm bg-red-500 inline-block" />
                                High
                            </span>
                            <span className="flex items-center gap-1.5">
                                <span className="w-3 h-3 rounded-sm bg-amber-400 inline-block" />
                                Medium
                            </span>
                            <span className="flex items-center gap-1.5">
                                <span className="w-3 h-3 rounded-sm bg-green-500 inline-block" />
                                Low
                            </span>
                        </div>
                    </div>
                    <div className="grid grid-cols-5 gap-2">
                        {riskMap.map(({ name, risk }) => (
                            <button
                                key={name}
                                onClick={() => handleToggleRisk(name)}
                                className="rounded-lg px-2 py-3 flex flex-col items-center justify-center text-center gap-1 hover:opacity-80 transition-opacity"
                                style={{ backgroundColor: riskColors[risk].bg }}
                                title="Click to manually update risk level"
                            >
                                <span className="text-white text-xs font-medium leading-tight">
                                    {name}
                                </span>
                            </button>
                        ))}
                    </div>
                </div>

                {/* Recent Activity Mini-Feed */}
                <div className="bg-white dark:bg-gray-800 rounded-xl p-5 shadow-sm border border-gray-100 dark:border-gray-700 transition-colors flex flex-col h-full">
                    <div className="flex items-center justify-between mb-4">
                        <h3 className="font-semibold text-gray-800 dark:text-gray-100 text-sm">
                            Recent Activity
                        </h3>
                        <button
                            onClick={handleSimulateEvent}
                            className="p-1 hover:bg-gray-100 dark:hover:bg-gray-700 rounded text-gray-400 dark:text-gray-500 transition-colors"
                            title="Simulate incoming event"
                        >
                            <Activity size={16} />
                        </button>
                    </div>

                    {/* Slice to show only the 5 most recent logs on the dashboard card */}
                    <div className="space-y-4 flex-1">
                        {logs.slice(0, 5).map(({ id, color, text, time }) => (
                            <div
                                key={id}
                                className="flex gap-3 animate-in fade-in slide-in-from-left-2 duration-300"
                            >
                                <div
                                    className="w-2 h-2 rounded-full mt-1.5 flex-shrink-0"
                                    style={{ backgroundColor: color }}
                                />
                                <div>
                                    <p className="text-xs text-gray-700 dark:text-gray-300 leading-snug transition-colors">
                                        {text}
                                    </p>
                                    <p className="text-xs text-gray-400 dark:text-gray-500 mt-0.5 transition-colors">
                                        {time}
                                    </p>
                                </div>
                            </div>
                        ))}
                    </div>

                    {/* TRIGGER LOGS MODAL */}
                    <button
                        onClick={() => setIsLogsModalOpen(true)}
                        className="mt-4 text-xs text-teal-600 dark:text-teal-400 font-medium hover:underline w-full text-center pt-3 border-t border-gray-50 dark:border-gray-700/50 transition-colors"
                    >
                        View Full Logs
                    </button>
                </div>
            </div>
        </Layout>
    );
}
